language: ruby
rvm:
- 2.2.0
env:
- DB=sqlite
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake test
deploy:
  provider: heroku
  api_key:
    secure: fLH/Pm28cxzQFUT1YpYv6u94SmzY9lLNg+yeVFzYj9EoRNapPsGj+ZInavJl+TvcnpId1FTXhZmG/xTDnuF6lMFSUPgqu2o6Rqoaln5103+ASwRKNTP5tFzCSOTf1zvoU+GtMiGh3/B80qct7APR7qK62LUNHBpCPmWDqRvhUSxxH3gpNJ1Kx2KAux0k8SaMQR+tsv2jwa+lImFlYN5xVRaztXp0/F4rizgqvhnW0w87/k+1RRFL88PAQsFb+xEQCziC5IBDRuFiMARmKElX9eRzyyRdvnW2VMc1eJSlABIcyp/3sDVlMZtYMltg0Y7nmyejxC5wFhwAzKidyb2P/6nh4e00XOikVzV/Q7niK7I4FifgYpLmp7eMnv3QLg1zWzFBRlYS+4ZGste0RnI5UA/WohPN0o+7EtIcAvGivg2esVm1L/zFC4ynNjG1M1UHvIKA+0B0deej04CKVCHKaLsbBDOf+FEKb8EcDO+hNovrEWsCSzYSTnRf5hzpAMlDyh3yEvWRw50qSftZddGkbziIEZOMuU3r4lGqBUD9SzoaAdrrRCz2uo0Kj/oQ+X9ZT5IOmOBQhIrtifiKYGdI2m9qfxUrT8PQilUt62Gryn+UATjCdeGpgXIPDDPR2mlKpqvS9EbiQRRncjTc5eu3NDseoAVGSu3KigvldE3Sj2Y=
  app: wrestlingapp
  on:
    repo: jcwimer/wrestlingApp
