sudo: required
language: minimal
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
env:
- DOCKER_COMPOSE_VERSION=1.22.0
script:
- bash bin/run-tests-with-docker.sh
deploy:
  provider: heroku
  api_key:
    secure: Ta9bwau8v0BxR92LZndTOPcxucNHQPe/sc9yqrSKvId1QqShm9PjfiOWAL6sjvCEnBxMJW5xvRXjovHWcpAS50IkUSAkFoYMypBhoUtXhGv7Bgy6POJanDEnVFY+h97lZW9aNiU7qVRprjS0+CdOGbPuNWscSDWgV017YmjiSx4ViRtZNyKV77kTx3bvK9A/yCzll+cVoRP4HoyFXVa9HO2xgUXFTm70nWEDuDcWA6z5EATheXhgC4450XFIR14P7CEs9kP1RWDDQ81OPKCjC2pkB24LKyMK75D7vt8DvwncSjw2oDbMQS4HgNr3RnekrjIoAlauuLQFLaZFXMNgP/UTuCE/5log0qyx3EJgrNC0WEfW7l0HkxWrll4HRulentK32eUDCvsjW6fSwcMMfkyLXspvz4GyjFazXAN8Bez8BN34QTj3klERRWEqTVz4wI1YYFkLXMu5U6tKvdV3Hs9inSVXzjlwtyGfR5mhSSQCXHKRpF0/z6npldYHeRBX9tUCBPjk+MUij4vNoPM3Aj6KrrfoQ42QncsmXETKHwOCPQ2qCQ3Bl8X4WqfeQqrL/JAxCzXrCatrnEXf3WmPOcdb8uzomK05sxF7PnIAnASdttQUJemAx+ygdaFDgT+ABctVsYh2IElKceo67/6eByGgbgOKFr7maznJO+po0B0=
  app: wrestlingapp
  on:
    repo: jcwimer/wrestlingApp
    branch: master
  run: rake db:migrate RAILS_ENV=production
