version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
         bash bin/run-tests-with-docker.sh
         
# https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci1/continuous-deployment-with-heroku.md
deployment:
  production:
    branch: master
    commands:
      - |
        cat >~/.netrc <<EOF
        machine api.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_TOKEN
        machine git.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_TOKEN
        EOF
      - chmod 600 ~/.netrc # Heroku cli complains about permissions without this
      - heroku git:remote -a wrestlingapp
      - git push heroku master
      - sleep 20s
      - heroku run rake db:migrate --app wrestlingapp