app:
  extends:
    file: docker-compose-common.yml
    service: app
  image: wrestlingdev-prod
  links:
    - db
  restart: always
  env_file:
    - ./prod.env
db:
  extends:
    file: docker-compose-common.yml
    service: db
  restart: always
  env_file:
    - ./prod.env
worker:
  extends:
    file: docker-compose-common.yml
    service: worker
  image: wrestlingdev-prod
  links:
    - db
  restart: always
  env_file:
    - ./prod.env
  healthcheck:
      test: ps -ef | grep rake | grep ruby
  command: bundle exec rake jobs:work RAILS_ENV=production

memcached:
  extends:
    file: docker-compose-common.yml
    service: memcached
  restart: always
