version: "3.3"
networks:
  database:
  caching:

volumes:
  mysql:

services:
  app:
    image: wrestlingdev-prod
    ports:
      - "80:80"
      - "443:443"
    networks:
      database:
      caching:
    restart: always
    env_file:
      - ./prod.env
    healthcheck: 
      test: curl --insecure https://127.0.0.1/

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    env_file:
      - ./prod.env
    networks:
      database:

  worker:
    image: wrestlingdev-prod
    networks:
      database:
      caching:
    restart: always
    env_file:
      - ./prod.env
    healthcheck:
        test: kill -0 1
    command: bundle exec bin/delayed_job -n 1 run


  memcached:
    image: memcached:1.5
    mem_limit: 64000000
    restart: always
    networks:
      caching: