version: "3.3"
networks:
  database:
  caching:

volumes:
  mysql:
  
services:
  app:
    image: wrestlingdev
    build:
      context: ../
      dockerfile: ./deploy/rails-prod-Dockerfile
    environment:
      - WRESTLINGDEV_DB_NAME=wrestlingtourney
      - WRESTLINGDEV_DB_USR=root
      - WRESTLINGDEV_DB_PWD=password
      - WRESTLINGDEV_DB_HOST=db
      - WRESTLINGDEV_DB_PORT=3306
      - WRESTLINGDEV_DEVISE_SECRET_KEY=2f29d49db6704377ba263f7cb9db085b386bcb301c0cd501126a674686ab1a109754071165b08cd72af03cec4642a4dd04361c994462254dd5d85e9594e8b9aa
      - WRESTLINGDEV_SECRET_KEY_BASE=077cdbef5c2ccf22543fb17a67339f234306b7fa2e1e4463d851c444c10a5611829a2290b253da78339427f131571fac9a42c83d960b2d25ecc10a4a0a7ce1a2
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=
      - MEMCACHIER_PASSWORD=
    networks:
      database:
      caching:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck: 
      test: curl --insecure https://127.0.0.1/

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
    networks:
      database:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  worker:
    image: wrestlingdev
    environment:
      - WRESTLINGDEV_DB_NAME=wrestlingtourney
      - WRESTLINGDEV_DB_USR=root
      - WRESTLINGDEV_DB_PWD=password
      - WRESTLINGDEV_DB_HOST=db
      - WRESTLINGDEV_DB_PORT=3306
      - WRESTLINGDEV_DEVISE_SECRET_KEY=2f29d49db6704377ba263f7cb9db085b386bcb301c0cd501126a674686ab1a109754071165b08cd72af03cec4642a4dd04361c994462254dd5d85e9594e8b9aa
      - WRESTLINGDEV_SECRET_KEY_BASE=077cdbef5c2ccf22543fb17a67339f234306b7fa2e1e4463d851c444c10a5611829a2290b253da78339427f131571fac9a42c83d960b2d25ecc10a4a0a7ce1a2
      - MEMCACHIER_SERVERS=memcached:11211
      - MEMCACHIER_USERNAME=
      - MEMCACHIER_PASSWORD=
    networks:
      database:
      caching:
    restart: always
    healthcheck:
        test: kill -0 1
    command: bundle exec rake jobs:work RAILS_ENV=production
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  memcached:
    image: memcached:1.5
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.10'
          memory: 64M
    restart: always
    networks:
      caching:

