app:
  image: registry:5000/wrestlingdev:dev
  extends:
    file: docker-compose-common.yml
    service: app
  environment:
    - WRESTLINGDEV_DB_NAME=wrestlingtourney
    - WRESTLINGDEV_DB_USR=root
    - WRESTLINGDEV_DB_PWD=password
    - WRESTLINGDEV_DB_HOST=db
    - WRESTLINGDEV_DB_PORT=3306
    - WRESTLINGDEV_DEVISE_SECRET_KEY=2f29d49db6704377ba263f7cb9db085b386bcb301c0cd501126a674686ab1a109754071165b08cd72af03cec4642a4dd04361c994462254dd5d85e9594e8b9aa
    - WRESTLINGDEV_SECRET_KEY_BASE=077cdbef5c2ccf22543fb17a67339f234306b7fa2e1e4463d851c444c10a5611829a2290b253da78339427f131571fac9a42c83d960b2d25ecc10a4a0a7ce1a2
    - MEMCACHIER_SERVERS=memcached:11211
    - MEMCACHIER_USERNAME=
    - MEMCACHIER_PASSWORD=
  links:
    - db
    - memcached
  restart: always

db:
  extends:
    file: docker-compose-common.yml
    service: db
  environment:
    - MYSQL_ROOT_PASSWORD=password
  restart: always

worker:
  image: registry:5000/wrestlingdev:dev
  extends:
    file: docker-compose-common.yml
    service: worker
  environment:
    - WRESTLINGDEV_DB_NAME=wrestlingtourney
    - WRESTLINGDEV_DB_USR=root
    - WRESTLINGDEV_DB_PWD=password
    - WRESTLINGDEV_DB_HOST=db
    - WRESTLINGDEV_DB_PORT=3306
    - WRESTLINGDEV_DEVISE_SECRET_KEY=2f29d49db6704377ba263f7cb9db085b386bcb301c0cd501126a674686ab1a109754071165b08cd72af03cec4642a4dd04361c994462254dd5d85e9594e8b9aa
    - WRESTLINGDEV_SECRET_KEY_BASE=077cdbef5c2ccf22543fb17a67339f234306b7fa2e1e4463d851c444c10a5611829a2290b253da78339427f131571fac9a42c83d960b2d25ecc10a4a0a7ce1a2
    - MEMCACHIER_SERVERS=memcached:11211
    - MEMCACHIER_USERNAME=
    - MEMCACHIER_PASSWORD=
  links:
    - db
    - memcached
  restart: always
  healthcheck:
      test: ps -ef | grep rake | grep ruby
  command: bundle exec rake jobs:work RAILS_ENV=production

memcached:
  extends:
    file: docker-compose-common.yml
    service: memcached
  restart: always

