receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  filter/queue-polling:
    error_mode: ignore
    traces:
      span:
        - 'status.code != STATUS_CODE_ERROR and end_time_unix_nano - start_time_unix_nano < 100000000 and IsMatch(name, "^SolidQueue::(ReadyExecution|ScheduledExecution|Process|Semaphore|BlockedExecution) query$")'
        - 'status.code != STATUS_CODE_ERROR and end_time_unix_nano - start_time_unix_nano < 100000000 and name == "ActiveRecord.transaction" and IsMatch(attributes["code.namespace"], "^SolidQueue::(ReadyExecution|ScheduledExecution|Process)$")'
  batch:

connectors:
  span_metrics:
    histogram:
      explicit:
        buckets: [5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s, 2.5s, 5s, 10s]
    dimensions:
      - name: http.route
      - name: http.request.method
      - name: http.response.status_code
      - name: db.system
      - name: code.namespace
      - name: channel_class
      - name: action
    exemplars:
      enabled: true
    aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE
    metrics_flush_interval: 15s

exporters:
  otlp_http/jaeger:
    endpoint: http://jaeger:4318
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/queue-polling, batch]
      exporters: [otlp_http/jaeger, span_metrics]
    metrics:
      receivers: [span_metrics]
      processors: [batch]
      exporters: [prometheus]
