production:
  tournament_cleanup_job:
    class: TournamentCleanupJob
    schedule: every day at 3am
    queue: default

development:
  tournament_cleanup_job:
    class: TournamentCleanupJob
    schedule: every day at 3am
    queue: default 