apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wrestlingdev-app-ingress-external
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  rules:
  - host: wrestlingdev.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wrestlingdev-app
            port:
              number: 80
  tls:
    - hosts:
      - wrestlingdev.com
      secretName: letsencrypt-prod
