apiVersion: v1
kind: Secret
metadata:
  name: wrestlingdev-secrets
type: Opaque
#data:
stringData:
  dbusername: root
  dbpassword: PUT_SECRET_HERE
  devisesecretkey: PUT_SECRET_HERE get from running rails secret
  railssecretkey: PUT_SECRET_HERE get from running rails secret
  emailpassword: PUT_EMAIL_PASSWORD_HERE
  gmailemail: PUT EMAIL ADDRESS HERE