apiVersion: v1
kind: Secret
metadata:
  name: wrestlingdev-secrets
type: Opaque
#data:
stringData:
  dbusername: root
  dbpassword: PUT_SECRET_HERE
  dbhost: wrestlingdev-mariadb (if using the mariadb-standalone from this repo, otherwise use your hostname for your database)
  devisesecretkey: PUT_SECRET_HERE get from running rails secret
  railssecretkey: PUT_SECRET_HERE get from running rails secret
  emailpassword: PUT_EMAIL_PASSWORD_HERE
  gmailemail: PUT EMAIL ADDRESS HERE
  influxdb_database: PUT INFLUXDB DATABASE NAME HERE
  influxdb_hostname: PUT INFLUXDB HOSTNAME OR IP HERE
  influxdb_port: PUT INFLUXDB PORT HERE