apiVersion: v1
kind: Secret
metadata:
  name: wrestlingdev-secrets
type: Opaque
#data:
stringData:
  # REQUIRED
  dbusername: root # if using the mariadb-standalone from this repo, otherwise use your username for your database
  dbpassword: PUT_SECRET_HERE # db password
  dbhost: wrestlingdev-mariadb # if using the mariadb-standalone from this repo, otherwise use your hostname for your database
  devisesecretkey: PUT_SECRET_HERE # get from running rails secret
  railssecretkey: PUT_SECRET_HERE # get from running rails secret
  gmailpassword: PUT_EMAIL_PASSWORD_HERE # gmail password
  gmailemail: PUT EMAIL ADDRESS HERE
  passenger_pool_size: "2"
  # OPTIONAL
  # DELETE THESE LINES IF YOU'RE NOT USING THEM
  influxdb_database: PUT INFLUXDB DATABASE NAME HERE
  influxdb_hostname: PUT INFLUXDB HOSTNAME OR IP HERE
  influxdb_port: PUT INFLUXDB PORT HERE
  rclone_type: s3
  rclone_extra_args: # example --no-check-certificate for self signed ssl minio certs
  rclone_path: # path to put the backup, for example this would be the bucket name for s3
  # required if rclone_type is s3
  s3_access_id:
  s3_access_key:
  s3_endpoint:
  s3_region:
